server:
  port: 8080

spring:
  application:
    name: spring-camel-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
camel:
  servlet:
    mapping:
      context-path: /simon-sprint-camel/*

management:
  endpoints:
    web:
      exposure:
        include: health, info, camelroutes

simon:
  endpoint:
    test:
      clientes: http://localhost:8081/ws/clientes
    seguros-mundial:
      consulta-vehiculo-RCE-homologado: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
