server:
  port: 8080

spring:
  application:
    name: spring-camel-gateway
  cloud:
    consul:
      host: sm-dev-refactor-discovery-lb-4476a00ba6412662.elb.us-east-1.amazonaws.com
      port: 8500
      discovery:
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
camel:
  main:
    use-breadcrumb: true
  servlet:
    mapping:
      context-path: /simon-sprint-camel/*

management:
  endpoints:
    web:
      exposure:
        include: health, info, camelroutes

simon:
  soap-configs:
    seguros-mundial:
      namespace: "http://www.mundialseguros.com.co/"
    banco-test:
      namespace: "https://api.bancotest.com.co/services/"
  endpoint:
    fineract:
      search-clients: https://demo.mifos.io/fineract-provider/api/v2/clients/search
      groups: https://demo.mifos.io/fineract-provider/api/v1/groups
    refactor-dev:
      devices: https://api.refactor.dev.internal:9090/api-refactor/devices
    datos-colombia:
      lista-paquetes: https://datosabiertos.bogota.gov.co/api/3/action/package_list
    test:
      clientes: http://localhost:8081/ws/clientes
    seguros-mundial:
      consulta-vehiculo-RCE-homologado: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      anular-poliza: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      calcular-poliza: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      confirmar-expedicion: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consulta-vehiculo-RCE: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-convenio: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      calcular-corto-plazo: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-declaraciones: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-formulario: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tomador: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-runt: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-runt-doc: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-planes-clausulados: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-propietarios: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-puntos-papeleria: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-rangos-papeleria: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-papeleria-disponible: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipo-poliza: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-datos-declaraciones: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-poliza-ap: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      descargar-poliza-electronica: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      descargar-poliza-formulario: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      descargar-poliza-soap-client: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      descargar-poliza-patente-soap: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      expedir-poliza-rcap: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      expedir-poliza-rcap-obligatorio: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      expedir-segurisimo: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      new-consultar-info-runt-doc: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      solicitar-papeleria: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-cartera: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-clases: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-departamentos: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-estado-formulario: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-formularios-disponibles: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-formularios-expedir: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-bd: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-formulario: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-formulario-exp: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-tomador: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-info-vehiculo: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-lineas: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-lineas-marca: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-marcas: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-motivos-anulacion: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-motivos-reemplazo: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-municipios: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-municipios-dpto: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-ocupaciones: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-servicios: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tarifas: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-direccion: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-documento: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-empresa: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-persona: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-tipos-telefono: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-ult-estado-formulario: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-vigencia-placa: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      consultar-cnt-ap: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      expedir-poliza-ap-xml: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      expedir-poliza-xml: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      generar-tasa-runt: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
      validar-placa-tarifa-pais: https://preprodsoapwssoatyapconsultarunt.mundialseguros.com.co:8443/SOATMundial.asmx
